version: '3.8'

services:
  dermalab-ui:
    build:
      context: ./ai-chatbot
      dockerfile: Dockerfile
    container_name: dermalab-ui
    command: ["/bin/sh", "-c", "npm run db:migrate && pnpm start"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    networks:
      - dermalab
      
  
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dermalab

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - dermalab


networks:
  dermalab:
    external: false


volumes:
  postgres_data: